/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AlbumAlbumIdRouteImport } from './routes/album/$albumId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AlbumAlbumIdRReviewCodeRouteImport } from './routes/album/$albumId/r/$reviewCode'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRReviewCodeRoute = AlbumAlbumIdRReviewCodeRouteImport.update({
  id: '/r/$reviewCode',
  path: '/r/$reviewCode',
  getParentRoute: () => AlbumAlbumIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/album/$albumId': typeof AlbumAlbumIdRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/album/$albumId/r/$reviewCode': typeof AlbumAlbumIdRReviewCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/album/$albumId': typeof AlbumAlbumIdRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/album/$albumId/r/$reviewCode': typeof AlbumAlbumIdRReviewCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/album/$albumId': typeof AlbumAlbumIdRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/album/$albumId/r/$reviewCode': typeof AlbumAlbumIdRReviewCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/admin/users'
    | '/album/$albumId'
    | '/api/upload'
    | '/user/$username'
    | '/api/auth/$'
    | '/album/$albumId/r/$reviewCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/admin/users'
    | '/album/$albumId'
    | '/api/upload'
    | '/user/$username'
    | '/api/auth/$'
    | '/album/$albumId/r/$reviewCode'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/admin/users'
    | '/album/$albumId'
    | '/api/upload'
    | '/user/$username'
    | '/api/auth/$'
    | '/album/$albumId/r/$reviewCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  UserUsernameRoute: typeof UserUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId/r/$reviewCode': {
      id: '/album/$albumId/r/$reviewCode'
      path: '/r/$reviewCode'
      fullPath: '/album/$albumId/r/$reviewCode'
      preLoaderRoute: typeof AlbumAlbumIdRReviewCodeRouteImport
      parentRoute: typeof AlbumAlbumIdRoute
    }
  }
}

interface AlbumAlbumIdRouteChildren {
  AlbumAlbumIdRReviewCodeRoute: typeof AlbumAlbumIdRReviewCodeRoute
}

const AlbumAlbumIdRouteChildren: AlbumAlbumIdRouteChildren = {
  AlbumAlbumIdRReviewCodeRoute: AlbumAlbumIdRReviewCodeRoute,
}

const AlbumAlbumIdRouteWithChildren = AlbumAlbumIdRoute._addFileChildren(
  AlbumAlbumIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  UserUsernameRoute: UserUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
