/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsernameRouteImport } from './routes/user/$username'
import { Route as ReviewReviewIdRouteImport } from './routes/review/$reviewId'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AlbumAlbumIdRouteImport } from './routes/album/$albumId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewReviewIdRoute = ReviewReviewIdRouteImport.update({
  id: '/review/$reviewId',
  path: '/review/$reviewId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumIdRoute = AlbumAlbumIdRouteImport.update({
  id: '/album/$albumId',
  path: '/album/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/album/$albumId': typeof AlbumAlbumIdRoute
  '/api/upload': typeof ApiUploadRoute
  '/review/$reviewId': typeof ReviewReviewIdRoute
  '/user/$username': typeof UserUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/album/$albumId'
    | '/api/upload'
    | '/review/$reviewId'
    | '/user/$username'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/album/$albumId'
    | '/api/upload'
    | '/review/$reviewId'
    | '/user/$username'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/album/$albumId'
    | '/api/upload'
    | '/review/$reviewId'
    | '/user/$username'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AlbumAlbumIdRoute: typeof AlbumAlbumIdRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ReviewReviewIdRoute: typeof ReviewReviewIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$reviewId': {
      id: '/review/$reviewId'
      path: '/review/$reviewId'
      fullPath: '/review/$reviewId'
      preLoaderRoute: typeof ReviewReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumId': {
      id: '/album/$albumId'
      path: '/album/$albumId'
      fullPath: '/album/$albumId'
      preLoaderRoute: typeof AlbumAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AlbumAlbumIdRoute: AlbumAlbumIdRoute,
  ApiUploadRoute: ApiUploadRoute,
  ReviewReviewIdRoute: ReviewReviewIdRoute,
  UserUsernameRoute: UserUsernameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
